@switch($element['element'])
    @case('input')
        <x-guide-x.form.input 
            :name="$element['name']"
            :label="$element['label']"
            :value="$element['value']"
            :type="$element['inputType']" 
            :id="$element['id']"
            :placeholder="$element['placeholder']" 
            :required="$element['required']"
            :for="$element['id']"
            :wrapClasses="$element['wrapClasses']"
            :labelClasses="$element['labelClasses']"
            :elementClasses="$element['elementClasses']"
            :actionOneName="$element['actionOneName']"
            :actionOneAttributes="$element['actionOneAttributes']"
            :actionTwoName="$element['actionTwoName']"
            :actionTwoAttributes="$element['actionTwoAttributes']"
            :max="$element['max'] ?? ''"
            :min="$element['min'] ?? ''"
            :step="$element['step'] ?? ''"
            :autofocus="$element['autofocus'] ?? ''"
            :readOnly="$element['readOnly'] ?? ''"
        />
        @break
    @case('textarea')
        <x-guide-x.form.textarea 
            :name="$element['name']"
            :label="$element['label']"
            :value="$element['value']"
            :id="$element['id']"
            :placeholder="$element['placeholder']" 
            :required="$element['required']"
            :for="$element['id']"
            :wrapClasses="$element['wrapClasses']"
            :labelClasses="$element['labelClasses']"
            :elementClasses="$element['elementClasses']"
            :rows="$element['rows']"
            :cols="$element['cols']"
            :actionOneName="$element['actionOneName']"
            :actionOneAttributes="$element['actionOneAttributes']"
            :actionTwoName="$element['actionTwoName']"
            :actionTwoAttributes="$element['actionTwoAttributes']"
            :autofocus="$element['autofocus'] ?? ''"
        />
        @break
    @case('select')
        <x-guide-x.form.select 
            :name="$element['name']"
            :label="$element['label']"
            :value="$element['value']"
            :id="$element['id']"
            :size="$element['size'] ?? 1"
            :required="$element['required']"
            :for="$element['id']"
            :wrapClasses="$element['wrapClasses']"
            :labelClasses="$element['labelClasses']"
            :elementClasses="$element['elementClasses']"
            :options="$element['options']"
            :actionOneName="$element['actionOneName']"
            :actionOneAttributes="$element['actionOneAttributes']"
            :actionTwoName="$element['actionTwoName']"
            :actionTwoAttributes="$element['actionTwoAttributes']"
            :multiple="$element['multiple']"
            :placeholder="$element['placeholder']"
            :currentTranslationLanguage="$element['currentTranslationLanguage']"
            :autofocus="$element['autofocus'] ?? ''"
        />
        @break
    @case('input-checkbox')
        <x-guide-x.form.checkbox 
            :name="$element['name']"
            :type="$element['inputType']"
            :value="$element['value']"
            :metaValues="$element['metaValues']"
            :label="$element['label']"
            :placeholder="$element['placeholder']" 
            :id="$element['id']"
            :required="$element['required']"
            :wrapClasses="$element['wrapClasses']"
            :labelClasses="$element['labelClasses']"
            :actionOneName="$element['actionOneName']"
            :actionOneAttributes="$element['actionOneAttributes']"
            :actionTwoName="$element['actionTwoName']"
            :actionTwoAttributes="$element['actionTwoAttributes']"
            :autofocus="$element['autofocus'] ?? ''"
        />
        @break
    @case('input-file')
        <x-guide-x.form.file 
            :name="$element['name']"
            :label="$element['label']"
            :value="$element['value']"
            :type="$element['inputType']" 
            :id="$element['id']"
            :placeholder="$element['placeholder']" 
            :required="$element['required']"
            :for="$element['id']"
            :wrapClasses="$element['wrapClasses']"
            :labelClasses="$element['labelClasses']"
            :elementClasses="$element['elementClasses']"
            :multiple="$element['multiple']"
            :maximumFiles="$element['maximumFiles']"
            :fileNameLabel="$element['fileNameLabel']"
            :accept="$element['accept']"
            :actionOneName="$element['actionOneName']"
            :actionOneAttributes="$element['actionOneAttributes']"
            :actionTwoName="$element['actionTwoName']"
            :actionTwoAttributes="$element['actionTwoAttributes']"
            :media="$element['media']"
            :media_deletion_url="$element['media_deletion_url']"
            :autofocus="$element['autofocus'] ?? ''"
        />
        @break
    @case('input-hidden')
        <x-guide-x.form.hidden 
            :name="$element['name']"
            :value="$element['value']"
            :type="$element['inputType']" 
            :id="$element['id']"
            :elementClasses="$element['elementClasses']"
        />
        @break
    @case('input-date-time')
        <x-guide-x.form.date-time
            :name="$element['name']"
            :label="$element['label']"
            :value="$element['value']"
            :type="$element['inputType']" 
            :id="$element['id']"
            :placeholder="$element['placeholder']" 
            :required="$element['required']"
            :for="$element['id']"
            :wrapClasses="$element['wrapClasses']"
            :labelClasses="$element['labelClasses']"
            :elementClasses="$element['elementClasses']"
            :autoComplete="$element['autoComplete']"
            :minDate="$element['minDate']"
            :maxDate="$element['maxDate']"
            :actionOneName="$element['actionOneName']"
            :actionOneAttributes="$element['actionOneAttributes']"
            :actionTwoName="$element['actionTwoName']"
            :actionTwoAttributes="$element['actionTwoAttributes']"
            :autofocus="$element['autofocus'] ?? ''"
        />
        @break
    @case('input-custom-has-many')
        <x-guide-x.form.custom-has-many
            :type="$element['inputType']" 
            :name="$element['name']" 
            :value="$element['value']" 
            :label="$element['label']"
            :title="$element['title']"
            :id="$element['id']"
            :elements="$element['elements']"
            :addButtonLabel="$element['addButtonLabel']" 
            :deleteAllButtonLabel="$element['deleteAllButtonLabel']"
            :wrapClasses="$element['wrapClasses']"
            :labelClasses="$element['labelClasses']"
            :required="$element['required']"
            :autofocus="$element['autofocus'] ?? ''"
        />
        @break
    @case('google-map')
        <x-guide-x.form.google-map 
            :label="$element['label']"
            :id="$element['id']"
            :wrapClasses="$element['wrapClasses']"
            :labelClasses="$element['labelClasses']"
            :elementClasses="$element['elementClasses']"
        />
        @break
    @default
        
@endswitch